// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs7rK2fnfsbzQzfgXjERBqRjJmCt7lR_w',
    appId: '1:658658514740:web:e0277ae9ed546031187761',
    messagingSenderId: '658658514740',
    projectId: 'flt-spotify',
    authDomain: 'flt-spotify.firebaseapp.com',
    storageBucket: 'flt-spotify.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs7rK2fnfsbzQzfgXjERBqRjJmCt7lR_w',
    appId: '1:658658514740:android:350e57ef3a6c4352187761',
    messagingSenderId: '426509858399',
    projectId: 'flt-spotify',
    storageBucket: 'flt-spotify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs7rK2fnfsbzQzfgXjERBqRjJmCt7lR_w',
    appId: '1:658658514740:ios:d1d39473c7bb76dc187761',
    messagingSenderId: '658658514740',
    projectId: 'flt-spotify',
    storageBucket: 'flt-spotify.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs7rK2fnfsbzQzfgXjERBqRjJmCt7lR_w',
    appId: '1:658658514740:ios:d1d39473c7bb76dc187761',
    messagingSenderId: '658658514740',
    projectId: 'flt-spotify',
    storageBucket: 'flt-spotify.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs7rK2fnfsbzQzfgXjERBqRjJmCt7lR_w',
    appId: '1:658658514740:web:11ac004391755727187761',
    messagingSenderId: '658658514740',
    projectId: 'flt-spotify',
    authDomain: 'flt-spotify.firebaseapp.com',
    storageBucket: 'flt-spotify.appspot.com',
  );
}
